language: android
script:
  - ./gradlew clean check
android:
  components:
    - build-tools-21.0.2
    - android-21
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository